# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

#trigger:
#- main
trigger: none

# default ppol runs a local agent and is available for public projects. Q. Does it work for private?
pool: default

# Only available if project is private. This runs the 'Azure Pipelines' agent automatically.
#pool:
# vmImage: 'windows-latest'

# Only available if project is private. This pool runs as ubuntu-latest which is twice the speed of windows-latest btw.
#pool: 'Azure Pipelines'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

